import streamlit as st
import numpy as np
import joblib

# Load the trained model and scaler
model = joblib.load("diabetes_prediction.pkl")
scaler = joblib.load("scaler.pkl")

# Page settings
st.set_page_config(
    page_title="Diabetes Prediction",
    page_icon="🩺",
    layout="centered"
)

# App title
st.title("🩺 Diabetes Prediction System")

st.write(
    "Enter the patient details below to predict "
    "whether the person is likely to have diabetes."
)

st.divider()

# Patient information
st.subheader("👤 Patient Information")

col1, col2 = st.columns(2)

with col1:
    pregnancies = st.number_input(
        "🤰 Pregnancies",
        min_value=0,
        max_value=20,
        value=1
    )

    glucose = st.number_input(
        "🩸 Glucose",
        min_value=0.0,
        max_value=200.0,
        value=120.0
    )

    blood_pressure = st.number_input(
        "💓 Blood Pressure",
        min_value=0.0,
        max_value=150.0,
        value=70.0
    )

    skin_thickness = st.number_input(
        "📏 Skin Thickness",
        min_value=0.0,
        max_value=100.0,
        value=20.0
    )

with col2:
    insulin = st.number_input(
        "💉 Insulin",
        min_value=0.0,
        max_value=900.0,
        value=80.0
    )

    bmi = st.number_input(
        "⚖️ BMI",
        min_value=0.0,
        max_value=70.0,
        value=25.0
    )

    diabetes_pedigree = st.number_input(
        "🧬 Diabetes Pedigree Function",
        min_value=0.0,
        max_value=3.0,
        value=0.5
    )

    age = st.number_input(
        "🎂 Age",
        min_value=1,
        max_value=120,
        value=30
    )

st.divider()

# Prediction button
if st.button("🔍 Predict Diabetes", use_container_width=True):

    input_data = np.array([[
        pregnancies,
        glucose,
        blood_pressure,
        skin_thickness,
        insulin,
        bmi,
        diabetes_pedigree,
        age
    ]])

    input_scaled = scaler.transform(input_data)

    prediction = model.predict(input_scaled)

    probability = model.predict_proba(input_scaled)[0][1]

    st.subheader("📊 Prediction Result")

    if prediction[0] == 1:
        st.error(
            f"⚠️ The model predicts a higher chance of diabetes.\n\n"
            f"Prediction probability: {probability:.2%}"
        )
    else:
        st.success(
            f"✅ The model predicts a lower chance of diabetes.\n\n"
            f"Prediction probability: {probability:.2%}"
        )

    st.info(
        "This prediction is generated by a machine learning model "
        "and should not be treated as a medical diagnosis."
    )

st.divider()

st.caption(
    "🤖 Logistic Regression | Diabetes Prediction"
)